#!/usr/bin/bash
#
# SimRacing Hub OS — SimHub setup helper
#
# Sets up SimHub to run on Linux through Wine:
#   1. Creates a dedicated Wine prefix.
#   2. Installs the .NET 4.8 runtime into it.
#   3. Runs the SimHub installer you downloaded.
#   4. Adds a "SimHub" launcher to your applications menu.
#
# SimHub's installer cannot be bundled into the OS for licensing reasons, so
# you download it once from the official site and this helper does the rest.

set -euo pipefail

PREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/simracinghub-os/simhub-prefix"
LAUNCHER="${XDG_DATA_HOME:-$HOME/.local/share}/simracinghub-os/simhub-launch.sh"
DESKTOP_FILE="$HOME/.local/share/applications/simracinghub-simhub.desktop"
DOWNLOAD_PAGE="https://www.simhubdash.com/download-2/"

echo "======================================================"
echo "   SimRacing Hub OS  —  SimHub setup"
echo "======================================================"
echo

# --- Step 1: find the SimHub installer --------------------------------------
echo "[1/4] Looking for the SimHub installer in your Downloads folder..."
INSTALLER="$(find "$HOME/Downloads" -maxdepth 1 -type f -iname 'simhub*.exe' 2>/dev/null | sort | tail -n1 || true)"

if [[ -z "$INSTALLER" ]]; then
    echo
    echo "  No SimHub installer found."
    echo
    echo "  Please do this, then run 'Set Up SimHub' again:"
    echo "    1. The SimHub download page will open in your browser."
    echo "    2. Download SimHub and save it to your Downloads folder."
    echo
    xdg-open "$DOWNLOAD_PAGE" >/dev/null 2>&1 || true
    read -rp "Press Enter to close."
    exit 1
fi
echo "      Found: $(basename "$INSTALLER")"
echo

# --- Step 2: prepare the Wine environment -----------------------------------
export WINEPREFIX="$PREFIX"
export WINEARCH="win64"
mkdir -p "$PREFIX"

echo "[2/4] Preparing the Wine environment and installing .NET 4.8..."
echo "      This takes several minutes. Warnings during this step are normal."
wineboot --init >/dev/null 2>&1 || true

if ! winetricks -q dotnet48; then
    echo
    echo "  The .NET 4.8 install did not finish cleanly. This usually works"
    echo "  on a second try — please run 'Set Up SimHub' again."
    read -rp "Press Enter to close."
    exit 1
fi
echo

# --- Step 3: install SimHub -------------------------------------------------
echo "[3/4] Starting the SimHub installer..."
echo
echo "  IMPORTANT — in the installer window, UNCHECK these (already handled):"
echo "    - .NET Framework"
echo "    - C++ redistributables"
echo "    - USB display drivers"
echo "  Then complete the installation normally."
echo
read -rp "Press Enter to launch the SimHub installer."
wine "$INSTALLER" || true
echo

# --- Step 4: create the launcher --------------------------------------------
echo "[4/4] Finishing up..."
SIMHUB_EXE="$(find "$PREFIX/drive_c" -iname 'SimHubWPF.exe' 2>/dev/null | head -n1 || true)"

if [[ -z "$SIMHUB_EXE" ]]; then
    echo
    echo "  SimHubWPF.exe was not found — the installation may have been"
    echo "  cancelled. Run 'Set Up SimHub' again to retry."
    read -rp "Press Enter to close."
    exit 1
fi

mkdir -p "$(dirname "$LAUNCHER")" "$(dirname "$DESKTOP_FILE")"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/bash
# SimHub launcher — generated by the SimRacing Hub OS SimHub setup helper.
export WINEPREFIX="$PREFIX"
exec wine "$SIMHUB_EXE" "\$@"
EOF
chmod +x "$LAUNCHER"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=SimHub
Comment=SimHub on SimRacing Hub OS
Exec=$LAUNCHER
Terminal=false
Categories=Game;
EOF

echo
echo "======================================================"
echo "  SimHub is installed. Look for 'SimHub' in your apps."
echo "======================================================"
read -rp "Press Enter to close."
